# -*- coding: utf-8 -*-
"""Mediana13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JskXyJr52yAZGs1YIVN7eIQURF-Qtdlh
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("estadistica").getOrCreate()
spark

#Utilizaremos la mediana para poder saber que nota se encuentra en el centro
#Una vez encontrada la nota nos indicará cuál es la nota ue divide al grupo en dos partes
data = [("Elvis",12),("Juan",18),
        ("Ronaldo",20),("Pablo",18),
         ("Alexis",14),("Cris",20),
          ("Ana",13),("Carlos",15),
           ("Fabian",15),("Carla",14),
            ("Fabiola",12),("Adriana",16),
             ("Fatima",20)]
columns = ["Nombre", "Nota"]
variable = spark.createDataFrame(data,columns)

var_mediana= variable.approxQuantile("Nota",[0.5], 0.0)

print("La mediana es: ",var_mediana)