# -*- coding: utf-8 -*-
"""Moda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2hhr_LkaYq8qwQZhgv3x6TvoxRluQmM
"""

#Vamos a utilizar un excel donde tendremos dos columnas. Almno y Nota.
#Implementaremos PySpark para analizar la moda en la lista de estudiantes
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("estadistica").getOrCreate()
spark

#Cargaremos los datos de los estudiantes, nombres y notas y luego podremos analizar que nota ha sido la más frecuente
#Una vez encontrada la nota más frecuente podremos realizar una sesión de reforzamiento
data = [("Elvis",12),("Juan",18),
        ("Ronaldo",20),("Pablo",18),
         ("Alexis",14),("Cris",20),
          ("Ana",13),("Carlos",15),
           ("Fabian",15),("Carla",14),
            ("Fabiola",12),("Adriana",16),
             ("Fatima",20)]
columns = ["Nombre", "Nota"]
variable = spark.createDataFrame(data,columns)

var_moda = variable.groupBy("Nota").count().orderBy(col("count").desc()).first()
print("La moda es: ",var_moda["Nota"])

data_var =[(12,1),(18,2),(20,1),(18,2),(14,1),(20,2),(13,1),(15,2),(15,1),(14,2),(12,1),(16,2),(20,1)]
columns_var = ["var1", "var2"]
variable_corr = spark.createDataFrame(data_var, columns_var)

correlacion = variable_corr.select(corr(col("var1"),col("var2")).alias("correlacion")).collect()[0]["correlacion"]

print("La correlacion es: ", correlacion)